[project]
name = "local-llm-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.124.2",
    "httpx>=0.27.2",
    "ollama>=0.6.1",
    "uvicorn>=0.38.0",
    "trafilatura>=1.12.2",
]
